version: '3.3'
services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysql  # user is root; supply any database for database
    ports:
      - 3306
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080